### ISSUE TITLE
:include: option not supported for code-block:: directive (rst)

### ISSUE THREAD

**Issue by ptitmain** [adamzap/landslide#105]
When using the code-block directive to include source code in a slide, it does not work when using the :include: option that allows to put the content into another file. For example:

=======
Level 0
=======

.. code-block:: java

   ok;

.. code-block:: java
   :include: file.java

produces:

<string>:9: (ERROR/3) Content block expected for the "code-block" directive; none found.

**Comment by gdyer** [comment]
The solution is to this (with optional line-numbering):

```
.. include:: tes.h
        :code: c++
        :number-lines:
```

Which produces
![tes](https://cloud.githubusercontent.com/assets/2645639/10062417/08ade8e0-6228-11e5-8692-2c4d274b39f2.png)

---

Using ``rst2html.py (Docutils 0.12 [release], Python 2.7.6, on linux2)``

**Comment by adamzap** [comment]
Thanks @gdyer!

**Comment by settermjd** [comment]
The following works for me:

```rst
.. code-block:: php

  :include: path/to/my/file.php
```
