### ISSUE TITLE
Render slide elements incrementally

### ISSUE THREAD

**Issue by ramnathv** [adamzap/landslide#113]
First off, amazing work with `landslide`. I find it the most elegant amongst all `HTML5` slide generation frameworks I have used. One of the features I miss is the ability to render slide elements incrementally. For example, using `<ul class = 'build'>` in Google's HTML5Slides would render the list elements incrementally. The same idea is incorporated into other frameworks like `deck.js`, `dzslides` etc.

Is it possible to implement this feature in `landslide`.

**Comment by adamzap** [comment]
I'm hoping to implement this in v2.0 after I deal with existing issues and pull requests then do some cleanup and refactoring.
