### ISSUE TITLE
Relative paths failure

### ISSUE THREAD

**Issue by fonnesbeck** [adamzap/landslide#147]
When using the `-r` switch for relative paths, landslide fails to create relative paths for some resources:

    <link rel="stylesheet" media="print" href="/Library/Python/2.7/site-packages/landslide-1.1.1-py2.7.egg/landslide/themes/default/css/print.css">
    <link rel="stylesheet" media="screen, projection" href="theme/css/screen.css">
    
    
    
    
    
    <script type="text/javascript" src="/Library/Python/2.7/site-packages/landslide-1.1.1-py2.7.egg/landslide/themes/default/js/slides.js"></script>

As you can see, `screen.css` is relative, but the other two resources are not.

I am running the current master on OS X 10.8.4 and Python 2.7.2.

**Comment by adamzap** [comment]
Thanks for the bug report!
