### ISSUE TITLE
Feature discussion: fragmented mode (i.e. let appear one bullet at the time)

### ISSUE THREAD

**Issue by davidedelvento** [adamzap/landslide#152]
See for example http://html5slides.googlecode.com/svn/trunk/template/index.html#7 for what I mean.

Now, since landslide is based on html5slides I would expect this feature to be available "for free", however I did not have enough time to study it yet, let me ask a few simple questions:

1) Is there any particular reason why this feature isn't available yet (e.g. conflicting with something else)?
2) Or is it just a matter of implementing some syntax in MD and reST to enable it (e.g. the class "build", see the source code for the above example at http://code.google.com/p/html5slides/source/browse/trunk/template/index.html)?
3) Or instead the display engine is different and therefore the fragmented display must be implemented also?

**Comment by adamzap** [comment]
I'm hoping to implement this in v2.0 after I deal with existing issues and pull requests then do some cleanup and refactoring.

Thanks for the resources!

**Comment by Fierthraix** [comment]
Is it possible to implement this in the short term by way of a macro?

It's pretty annoying and messy to deal with having multiple copies of the same slide with one bullet different each time (especially for un-centering the list so the reveals don't look bad).
