### ISSUE TITLE
after scrolldown in Overview, the page position is shift up~

### ISSUE THREAD

**Issue by idning** [adamzap/landslide#154]
![landslide-on-scrolldown](https://f.cloud.github.com/assets/1301031/1508349/5138774a-49ef-11e3-99cc-ef2614f0b640.png)

**Comment by tjwood100** [comment]
I see this in Firefox but not Chrom(e/ium). This can be fixed in the template slides.js by adding

                event.preventDefault();

in the case statements in  handleBodyKeyDown following prevSlide() and nextSlide().

**Comment by tjwood100** [comment]
Actually I see event.preventDefault is already present in the latest version. I was using a slides.js from a template based off an older version.

**Comment by adamzap** [comment]
@tjwood100 Thanks!
