### ISSUE TITLE
PDF generation is broken (from .rst)

### ISSUE THREAD

**Issue by fdev31** [adamzap/landslide#165]
When I try to generate a PDF I just get a "one sentence per slide" presentation, instead of say ~50 slides I obtain almost 300 ... Didn't try somewhere else if it's easily reproducible btw.

**Comment by adamzap** [comment]
I'm unable to reproduce this. It works for the example for me.

Could you paste some breaking restructured text so I can debug it?

Thanks

**Comment by adamzap** [comment]
Reopen this ticket if you're still having problems
