### ISSUE TITLE
slides are shifted

### ISSUE THREAD

**Issue by grmlber** [adamzap/landslide#174]
Hi,
while I was creating my first real presentation using landslide I noticed that the slides seem to be shifted (not centered any more) after scrolling through them. As an example I attached the first slide of an example presentation and the 6th after clicking through the pages. The last page is perfectly normal again. 

Since it only happens on self-rendered presentations, I guess it's a wrong configuration on my side, but I can't find it.
 UPDATE:  the issue only happens when using the "arrow right" key. It doesn't occure using the space key.

I hope you have some ideas or fixes, have a great day,
Sebastian

![slide1](https://cloud.githubusercontent.com/assets/10638278/5843731/d77186f4-a1ae-11e4-8212-88106ff96c73.png)
![slide2](https://cloud.githubusercontent.com/assets/10638278/5843732/d775c53e-a1ae-11e4-8748-9c5039a98eb3.png)

**Comment by adamzap** [comment]
I'm having trouble reproducing this issue. Could you post an example source file that where it happens?

**Comment by adamzap** [comment]
Reopen this ticket if you're still having problems
