### ISSUE TITLE
Bug with multiple images

### ISSUE THREAD

**Issue by white-feather** [adamzap/landslide#177]
Using landslide 1.1.1 with default theme

    # Hello

    * chess

    ![chess](img/chess1.jpg)
    ![chess](img/chess1.jpg)

    * other

    ![other](img/mario.jpg)
    ![other](img/mario.jpg)

produces

![image](https://cloud.githubusercontent.com/assets/3597069/5992781/bced2306-aa37-11e4-9ff8-76524b20a5b0.png)

Adding the same image is ok but any other image does not display.

**Comment by adamzap** [comment]
Thanks for the bug report!
