### ISSUE TITLE
math_output do not work

### ISSUE THREAD

**Issue by mrkwjc** [adamzap/landslide#179]
I tried to enable MathJax with -m option for .rst slides but this simply didn't work. I have docutils 0.12. Others with the same problem?

Marek

**Comment by adamzap** [comment]
Run `landslide -m` on an `.rst` file containing this:

```
MathJax Test
============

\\[ \\left( \\sum_{k=1}^n a_k b_k \\right)^2 \\]

```

It works for me. Does it work for you?

**Comment by mrkwjc** [comment]
Doesn't work. I tried also with

:math:`\left( \\sum_{k=1}^n a_k b_k \\right)^2`

but without success. Can i get any debugging informations from landslide?

**Comment by adamzap** [comment]
That's odd.

You can try the `-b` flag, but I'm not sure that it will help.

The best thing to do is probably to look at the generated HTML file and debug from there.

**Comment by adamzap** [comment]
Reopen this ticket if you're still having problems

**Comment by con-f-use** [comment]
Just as a reference for future people who look at this issue.

The author might have used a custom theme or an old version of a theme that did not have this in it's `base.html`:

```
      <script type="text/javascript" src="{{ js.path_url }}"></script>
      {% endif %}
    {% endfor %}
    {% if math_output %}
      <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: { inlineMath: [['$','$'],['\\(','\\)']] }
        });
      </script>
      <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    {% endif %}
    <!-- /Javascripts -->
</head>
<body>
```

Happened to me.

**Comment by adamzap** [comment]
Thanks for the feedback!
