### ISSUE TITLE
The package structure is incorrect

### ISSUE THREAD

**Issue by bermanmaxim** [adamzap/landslide#181]
Hello, currently `import landscape` imports no symbols other than the ones defined in `__init__.py`. For instance, `landscape.generator` is not defined. `import landslide.main` works.

Moreover, the themes directory was not added in `/usr/local/lib/python2.7/dist-packages/landslide-1.1.3-py2.7.egg/` by `setup.py`, I had to copy it manually.

**Comment by adamzap** [comment]
You're referring to the master branch, right?

Do you have any suggestions? Maybe put statements like `from .generator import Generator` in `__init__.py`?

**Comment by bermanmaxim** [comment]
Yes, I was referring to the master branch.

A `from .generator import Generator` statement in `__init__.py` would work, but then its more logical to call the generator as `g = landslide.Generator(source='toto.md')`. If you'd rather stick to the instructions of the readme, where the generator is called as `g = landslide.generator.Generator(source='toto.md')`, I would rather put `from . import generator` in the `__init__.py`.

**Comment by adamzap** [comment]
I believe I have fixed the themes directory issue. I can generate presentations after installing via `setup.py`.

Could you grab master and try?

Thanks!

**Comment by bermanmaxim** [comment]
Hello, sure, I just tried it, adding the theme folder in the manifest did the trick.

**Comment by adamzap** [comment]
Awesome!

I'll close the issue then.

I'm curious though why you installed with `setup.py` instead of `pip`.

**Comment by bermanmaxim** [comment]
Well, it's because I followed these instructions on the Readme.md:

> If you want to stay on the edge:
> 
>    $ git clone https://github.com/adamzap/landslide.git
>    $ cd landslide
>    $ python setup.py build
>    $ sudo python setup.py install

Since you close the issue, remember to put `from . import generator` in your `__init__.py`, which was the main issue ;)

**Comment by adamzap** [comment]
Got it, thanks!
