### ISSUE TITLE
Error when only "print" stylesheet is presented

### ISSUE THREAD

**Issue by vbauer** [adamzap/landslide#186]

**Comment by vbauer** [comment]
In my theme I wanted to have only print.css (without screen.css), but got the following error:

```
➜  Lecture 18 - Geo git:(master) ✗ landslide lecture.md -i -t theme -d presentation.pdf
Copying theme theme directory to /Users/vbauer/Documents/workspace/java/internship-lectures/test/Lecture 18 - Geo/theme
Adding   lecture.md (markdown)
Embedded image img/GoogleApiClient.png
Embedded image img/geoDialog.png
Embedded image img/bubble_simple.png
Embedded image img/bubble_custom.png
No screen stylesheet provided in current theme
Error: 'dict object' has no attribute 'screen'
```

**Comment by adamzap** [comment]
Your theme should inherit from the default theme...or did you delete it?

Also, you could add a blank `screen.css` file in your theme directory. That's a simple way to bypass it.

**Comment by adamzap** [comment]
@vbauer Let me know if you need any more help

**Comment by vbauer** [comment]
@adamzap I added a blank screen.css and it helped to resolve this problem. Thank you for information.
