### ISSUE TITLE
Error: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by tiansiyuan** [adamzap/landslide#188]
with a file in Chinese

**Comment by adamzap** [comment]
- Which version are you using?
- Can you provide a file that causes it to fail?

**Comment by adamzap** [comment]
Closing until a response is received

**Comment by luwenhegithub** [comment]
I have encountered this problem.
I use the version 1.1.3-2.fc24.
I'm using Landslide on Fedora.
This response was translated using Google Translate.

**Comment by adamzap** [comment]
@luwenhegithub Could you provide a file that I can run through Landslide to reproduce the problem?
