### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by nobicycle** [adamzap/landslide#205]
Thank you very much for the excellent landslide.

Is there a configuration option to switch on full screen ("e")?, that can be placed at the top of an rst file, such as:

:skip-help: true
:version: 1.0 of 2018/07/30

**Comment by adamzap** [comment]
I'm not sure that I understand. Do you mean you want to change the shortcut key for full screen with an rst directive in your source file?

**Comment by nobicycle** [comment]
Not change the shortcut key, just switch on full screen state of the presentation as soon as it is loaded.
Yes, a directive, such as :full-screen: true

**Comment by adamzap** [comment]
This is not possible at the moment. I think you could do it in a custom theme though.
