### ISSUE TITLE
Error: markdown() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by wangkangquan** [adamzap/landslide#208]
```bash
$ landslide learn.md 
Adding   learn.md (markdown)
Error: markdown() takes exactly 1 argument (2 given)
```

running in Mac System.

```bash
$ landslide --version
landslide 1.1.3
```

**Comment by nonprofittechy** [comment]
Similar error on Windows with git bash and python 3.6.4--running both stable and the github latest version of landslide.

```
$ landslide hello_world_slides.md
Error: markdown() takes 1 positional argument but 2 were given
Adding   hello_world_slides.md (markdown)
```

**Comment by adamzap** [comment]
I'll try to fix this and cut a new release soon, thanks.

**Comment by adamzap** [comment]
After a few packaging mistakes, I've finally released `v.1.1.6`. Could you try it and let me know if the markdown issue is fixed? @wangkangquan @nonprofittechy 

Thanks!

**Comment by wangkangquan** [comment]
install:
```
$ sudo pip uninstall landslide
$ sudo pip install landslide
```
and then got the error like this:
```
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
```
try to fix it:
```
$ sudo pip install six --upgrade --ignore-installed six
```
and install again, it success!

but the generated HTML has not slide effect, thanks!

**Comment by adamzap** [comment]
Ok cool. I'll consider this fixed.

Let me know if you have any more trouble.

If you do a fresh install and are still not seeing slide effects, please open another issue with steps to reproduce. Thanks!

**Comment by nonprofittechy** [comment]
The upgrade solved it for me too, thanks. No errors when I did `git pull` and `python setup.py install`

**Comment by michel-slm** [comment]
Proper support for `markdown` >= 3.0 is added in https://github.com/adamzap/landslide/commit/e4005a418f851314ce272fbc8cb5f5e3100568ed after 1.1.6 is cut -- can we have a new release of `landslide` that includes this?

**Comment by adamzap** [comment]
I finally did it! Thanks for bugging me about it 😄
