### ISSUE TITLE
"Here's an example." link in README.md seems dead

### ISSUE THREAD

**Issue by boldandbusted** [adamzap/landslide#224]
Howdy. The link "Here's an example." in https://github.com/adamzap/landslide#publishing-your-presentation-online seems dead. The server seems offline - it doesn't 404, but it does resolve; my browser stalls at "Connecting...". Here's what it links to now: http://www.akei.com/presentations/2011-Djangocong/index.html. Cheers.

**Comment by adamzap** [comment]
You're right! I'll try to fix this soon.

**Comment by eli-b** [comment]
Hi Adam, your site seems to be up now, but the link is still dead. Do you remember what slideshow it pointed to?

**Comment by adamzap** [comment]
Would the other example in the README be sufficient? https://landslide-python.netlify.app/

**Comment by eli-b** [comment]
Frankly, I was hoping for a more impressive demo, since competing tools,
such as Darkside, have more polished demo slides
<https://ionelmc.github.io/python-darkslide/index.html>,
but anything is better than a 404.

**Comment by adamzap** [comment]
I just removed the link: https://github.com/adamzap/landslide/commit/0de3b3455d5f117a7e931bb99b77588fb1f7364a.

@eli-b Thanks for bumping this and for the feedback! You're welcome to use `python-darkslide` if you like it better. I'd be open to a pull request for a better example slideshow here if you want to make one though.
