### ISSUE TITLE
Works fine locally but not on Github Pages? 

### ISSUE THREAD

**Issue by joereddington** [adamzap/landslide#235]
Hello! 

Lovely bit of software, I adore it. 

I've got a repo [here](https://github.com/joereddington/paperwriting/) that contains my files.  When I open the html file locally everything is perfect, but on [Github pages](https://joereddington.github.io/paperwriting/) it renders as if it were straight html.  Any ideas what might have happened?

**Comment by joereddington** [comment]
Never mind - I didn't properly use the help - I needed to use some of the modifier flags.

**Comment by adamzap** [comment]
No worries. Glad you like it!

**Comment by joereddington** [comment]
OMG which flags did I use? Aggggh 

EDIT: it was -r

**Comment by adamzap** [comment]
@joereddington Glad you figured it out. Ping me if you need any help!
