### ISSUE TITLE
embed svg as dom instead of base64-url

### ISSUE THREAD

**Issue by flying-sheep** [adamzap/landslide#95]
`![svg](mypic.svg)` shold expand to `<svg><title>svg</title>...</svg>` instead of `<img alt="svg" src"data:image/svg+xml;base64,..."/>` if the `-i` flag or `embed = True` is specified

**Comment by adamzap** [comment]
The current method seems to work fine. If you have some reasoning as to why it should work in the way you have suggested, please reopen the ticket and let me know.

Thanks!
