### ISSUE TITLE
Add CLI option to enable all markdown extensions

### ISSUE THREAD

**Issue by davidblewett** [adamzap/landslide#99]
It would be nice to not have to explicitly enable each Markdown extension used in the presentation, but have all of them enabled. 

http://freewisdom.org/projects/python-markdown/Available_Extensions lists them all, but doesn't give you the exact name you have to pass to -x .

**Comment by adamzap** [comment]
I have linked to the [python markdown extensions documentation](http://pythonhosted.org//Markdown/extensions/index.html) in the README.

You have to pass in the extension name, so pass in `abbr` to get `markdown.extensions.abbr` loaded.

I think loading them all could be problematic as some users might experience unexpected behavior with their markup. They are extensions for a reason! :wink: 

Thanks!
